services:
  frontend:
    build:
      context: ./frontend
      dockerfile: development.Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    healthcheck:
        test: [ "CMD", "wget", "--spider", "http://frontend:3000/" ]
        interval: 30s
        timeout: 10s
        retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: development.Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/app
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://backend:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5