services:
  frontend:
    build:
      context: ./frontend
      dockerfile: development.Dockerfile
    restart: on-failure
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: development.Dockerfile
    restart: on-failure
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"