services:
  frontend:
    build:
      context: ./frontend
      dockerfile: production.Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5000:3000"

volumes:
  database_volume: